#
# Module manifest for module 'LazyWorker'
#
# Generated by: Antigravity
#
# Generated on: 2026-06-14
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'LazyWorker.psm1'

# Modules to import as nested modules
NestedModules = @(
    'Module\Search-String.psm1',
    'Module\Stop-ProcessWithDll.psm1',
    'Module\Log.psm1',
    'Module\Send-FileViaSSH.psm1',
    'Module\Get-AllFontName.psm1',
    'Module\LinuxCmd\Get-OomKillerHistory.psm1',
    'Module\Export-ProjectContext.psm1',
    'Module\New-AiProjectPattern.psm1'
)

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = 'd2e2ad47-7988-466d-8ca1-44754714f3aa'

# Author of this module
Author = 'anh.embedded, Embedded Nathan'

# Company or vendor of this module
CompanyName = 'NON'

# Copyright statement for this module
Copyright = '(c) 2026 anh.embedded, Embedded Nathan. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Lazy fucntion for automate'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Functions to export from this module, for best performance, do not use wildcards and do not withdraw them from the list.
FunctionsToExport = 
@('Search-String', 'Stop-ProcessWithDll', 'Write-Log', 'Send-FileViaSSH', 'Get-AllFontName', 'Get-OomKillerHistory', 'Export-ProjectContext', 'New-AiProjectPattern')

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

}
